Fix up compile time problems - except for unused parameters
git-svn-id: https://mydns-ng.svn.sourceforge.net/svnroot/mydns-ng@178 fff143f6-a9c2-4b89-8f93-78cb2c0259b0

diff --git a/mydns/branches/howard/pre-1.2.9/configure b/mydns/branches/howard/pre-1.2.9/configure
--- a/mydns/branches/howard/pre-1.2.9/configure
+++ b/mydns/branches/howard/pre-1.2.9/configure
@@ -18315,7 +18315,7 @@ _ACEOF
 
 					{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-					CFLAGS="-O -g -pg"
+					CFLAGS="-O2 -g -pg -Wp,-D_FORTIFY_SOURCE=2"
 					LDFLAGS="$LDFLAGS -pg"
 					PROFILE_ENABLED=yes
 
@@ -18399,7 +18399,7 @@ if test "${enable_debug+set}" = set; then
   enableval=$enable_debug;
 				if test "$enableval" = yes
 				then
-					CFLAGS="-O -g"
+					CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2"
 
 cat >>confdefs.h <<\_ACEOF
 #define DEBUG_ENABLED 1
@@ -18844,7 +18844,7 @@ if test "${enable_valgrind+set}" = set; then
 				then
 					{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-					CFLAGS="-O -g"
+					CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2"
 
 		ac_save_CFLAGS=$CFLAGS
 		CFLAGS="-fno-inline"
@@ -18984,7 +18984,7 @@ if test "${enable_strict_warnings+set}" = set; then
 				then
 					{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
-					CFLAGS="-O -g"
+					CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2"
 
 		ac_save_CFLAGS=$CFLAGS
 		CFLAGS="-W"
@@ -19092,6 +19092,63 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 			{ echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 			CFLAGS="$ac_save_CFLAGS -Wall"
+		else
+			{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+			CFLAGS=$ac_save_CFLAGS
+		fi
+
+
+
+		ac_save_CFLAGS=$CFLAGS
+		CFLAGS="-Wno-unused-parameter"
+		{ echo "$as_me:$LINENO: checking whether $CC accepts -Wno-unused-parameter" >&5
+echo $ECHO_N "checking whether $CC accepts -Wno-unused-parameter... $ECHO_C" >&6; }
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_prog_cc_optok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_prog_cc_optok=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		if test "$ac_cv_prog_cc_optok" = "yes"; then
+			{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+			CFLAGS="$ac_save_CFLAGS -Wno-unused-parameter"
 		else
 			{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
